import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headerStyles = {
    backgroundColor: "lightblue",
    padding: "1rem", 
  };

  const footerStyles = {
    backgroundColor: "ghostwhite",
    padding: "1rem", 
  };

  return (
    <html lang="en">
      <body>
        <header style={headerStyles}>
          <p>Header</p>
        </header>
        {children}
        <footer style={footerStyles}>
          <p>footer</p>
        </footer>
      </body>
    </html>
  );
}
